server:
  port: 8008
  servlet:
    context-path: /paiya-accountmanager/api/

# Database
spring:
  data:
    mongodb:
#      uri: "mongodb://admin:admin@localhost:27017/paiya_accountmanager"
      host: localhost
      port: 27017
      database: paiya_accountmanager
      username: ${PAIYA_DB_USERNAME:paiya}
      password: ${PAIYA_DB_PASSWORD:paiya}
